# Generated by Django 2.2.1 on 2019-12-01 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000, verbose_name='Decription of the memory')),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=13, verbose_name='Longitude')),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=12, verbose_name='Latitude')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='Time the memory has been posted.')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner of the memory')),
            ],
        ),
    ]
