# Generated by Django 2.2.1 on 2019-12-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memory',
            options={'ordering': ('-posted_at',)},
        ),
        migrations.AlterField(
            model_name='memory',
            name='latitude',
            field=models.DecimalField(decimal_places=20, max_digits=22, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='longitude',
            field=models.DecimalField(decimal_places=20, max_digits=23, verbose_name='Longitude'),
        ),
    ]
